### ISSUE TITLE
ensure only the slide loads on the phone and only the images load on desktop view

### ISSUE THREAD

**Issue by smsohan** [easyfindcare/care#17]

**Comment by xlgmokha** [comment]
Desktop:

![Screenshot from 2020-01-02 17-30-41](https://user-images.githubusercontent.com/80475/71701289-e3903300-2d85-11ea-859b-6b99c9b201d6.png)

Mobile:

![Peek 2020-01-02 17-31](https://user-images.githubusercontent.com/80475/71701294-e68b2380-2d85-11ea-87b9-dbcbc4d2b982.gif)
