### ISSUE TITLE
track all clicks on the sign-up button

### ISSUE THREAD

**Issue by smsohan** [easyfindcare/care#18]

**Comment by xlgmokha** [comment]
Info on publishing custom events can be found [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/events). 

We should be able to publish this event from [here](https://github.com/easyfindcare/easyfindcare.github.io/blob/f499ec96247614adaaa54a5ff4eb4d9e9e68ab18/assets/app.js#L59).

**Comment by xlgmokha** [comment]
https://github.com/easyfindcare/easyfindcare.github.io/commit/2b55cf4caa9f814c3b0ad387413dd20baaec8fe8
